name: Actions # name of the action (displayed in the github interface)
 
on: # event list
  pull_request: # on a pull request to each of these branches
    branches:
      - development
      - main
 
env: # environment variables (available in any part of the action)
  NODE_VERSION: 16
 
jobs: # list of things to do
  actions:
    name: Actions # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
 
      - name: Code Checkout
        uses: actions/checkout@v2
 
      - name: Install Dependencies
        run: npm ci

      - name: npm audit action
        uses: oke-py/npm-audit-action@v2.2.0
 
      - name: Code Linting
        run: npm run test:lint

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hub-mobile:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/hub-mobile:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/hub-mobile:buildcache,mode=max